#!/usr/bin/env cagent run
version: "2"

models:
  azure_model:
    provider: azure
    ## TODO: Replace with your Azure OpenAI deployment name
    model: gpt-4o
    # TODO: Replace with your Azure OpenAI base URL
    base_url: https://your-resource-name.cognitiveservices.azure.com
    provider_opts:
      api_version: 2025-01-01-preview

agents:
  root:
    model: azure_model
    description: An AI assistant to troubleshoot issues in your Kubernetes cluster
    instruction: |
      You are an AI assistant that will helps troubleshoot issues in a Kubernetes cluster. Be independent and proactive in your approach to diagnosing and resolving the connectivity issues and not ask for help unless absolutely necessary.

      You primary role is to:
      1. **Ask for Clarification**: If the user's request is ambiguous or lacks sufficient detail, ask clarifying questions to gather more information about the issue.
      2. **Information Gathering**: Use the available tools to gather information about the Kubernetes cluster, including checking events, logs, and using inspektor_gadget_observability tools to collect differetn types of data.
      2  **Solutioning **: Based on the information collected, come up with a plan to diagnose and resolve the issue. This may involve running specific commands, checking configurations, or analyzing logs.
      3  **Analysis **: Analyze the output from the tools to identify potential issues and their root causes.
      4  **Reporting**: Provide a summary of your findings and suggest next steps to resolve the issue.

      Note: Always try to use filtering or limits when running commands to avoid overwhelming amounts of data.

    toolsets:
      - type: mcp
        ref: docker:aks
        tools: [ "kubectl_resources", "kubectl_diagnostics", "insektor_gadget_observability" ]
        config:
          # TODO: Replace with the path to your kubeconfig file
          kubeconfig: PATH_TO_YOUR_KUBECONFIG
          ## TODO: Replace with the path to your Azure CLI config directory
          azure_dir: PATH_TO_YOUR_AZURE_CONFIG_DIR
          ## TODO: Replace with your Container User ID
          container_user: "1000"
          access_level: readwrite
